//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: MapData.proto
namespace proto.mapdata
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapData")]
  public partial class MapData : global::ProtoBuf.IExtensible
  {
    public MapData() {}
    
    private int? _mapID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? mapID
    {
      get { return _mapID; }
      set { _mapID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mapIDSpecified
    {
      get { return this._mapID != null; }
      set { if (value == (this._mapID== null)) this._mapID = value ? this.mapID : (int?)null; }
    }
    private bool ShouldSerializemapID() { return mapIDSpecified; }
    private void ResetmapID() { mapIDSpecified = false; }
    
    private string _mapName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapName
    {
      get { return _mapName; }
      set { _mapName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mapNameSpecified
    {
      get { return this._mapName != null; }
      set { if (value == (this._mapName== null)) this._mapName = value ? this.mapName : (string)null; }
    }
    private bool ShouldSerializemapName() { return mapNameSpecified; }
    private void ResetmapName() { mapNameSpecified = false; }
    
    private int? _mapXSize;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapXSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? mapXSize
    {
      get { return _mapXSize; }
      set { _mapXSize = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mapXSizeSpecified
    {
      get { return this._mapXSize != null; }
      set { if (value == (this._mapXSize== null)) this._mapXSize = value ? this.mapXSize : (int?)null; }
    }
    private bool ShouldSerializemapXSize() { return mapXSizeSpecified; }
    private void ResetmapXSize() { mapXSizeSpecified = false; }
    
    private int? _mapYSize;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mapYSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? mapYSize
    {
      get { return _mapYSize; }
      set { _mapYSize = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mapYSizeSpecified
    {
      get { return this._mapYSize != null; }
      set { if (value == (this._mapYSize== null)) this._mapYSize = value ? this.mapYSize : (int?)null; }
    }
    private bool ShouldSerializemapYSize() { return mapYSizeSpecified; }
    private void ResetmapYSize() { mapYSizeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<proto.mapdata.TerrainTileInfo> _tile_list = new global::System.Collections.Generic.List<proto.mapdata.TerrainTileInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"tile_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.mapdata.TerrainTileInfo> tile_list
    {
      get { return _tile_list; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.mapdata.TerrainGridInfo> _grid_list = new global::System.Collections.Generic.List<proto.mapdata.TerrainGridInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"grid_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.mapdata.TerrainGridInfo> grid_list
    {
      get { return _grid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TerrainTileInfo")]
  public partial class TerrainTileInfo : global::ProtoBuf.IExtensible
  {
    public TerrainTileInfo() {}
    
    private string _terrainName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"terrainName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string terrainName
    {
      get { return _terrainName; }
      set { _terrainName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool terrainNameSpecified
    {
      get { return this._terrainName != null; }
      set { if (value == (this._terrainName== null)) this._terrainName = value ? this.terrainName : (string)null; }
    }
    private bool ShouldSerializeterrainName() { return terrainNameSpecified; }
    private void ResetterrainName() { terrainNameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TerrainGridInfo")]
  public partial class TerrainGridInfo : global::ProtoBuf.IExtensible
  {
    public TerrainGridInfo() {}
    
    private proto.mapdata.TerrainType? _terrainType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"terrainType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.mapdata.TerrainType? terrainType
    {
      get { return _terrainType; }
      set { _terrainType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool terrainTypeSpecified
    {
      get { return this._terrainType != null; }
      set { if (value == (this._terrainType== null)) this._terrainType = value ? this.terrainType : (proto.mapdata.TerrainType?)null; }
    }
    private bool ShouldSerializeterrainType() { return terrainTypeSpecified; }
    private void ResetterrainType() { terrainTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TerrainType")]
    public enum TerrainType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LandRoad", Value=0)]
      LandRoad = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LandWall", Value=1)]
      LandWall = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WaterRoad", Value=2)]
      WaterRoad = 2
    }
  
}